image: node:latest

stages:
  - build
  - deploy

variables:
  FIREBASE_TOKEN: $FIREBASE_TOKEN

cache:
  paths:
    - node_modules/
    - build/

build:
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --token $FIREBASE_TOKEN